# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.binance import binance
from ccxt.abstract.binance import ImplicitAPI
from ccxt.base.types import Any
from ccxt.base.errors import InvalidOrder, BadRequest, AuthenticationError, NotSupported
import hashlib
import json


class aster(binance, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(aster, self).describe(), {
            'id': 'aster',
            'name': 'Aster Perpetual (Pro)',
            'pro': True,
            'has': {
                'CORS': None,
                'spot': False,
                'margin': False,
                'swap': True,
                'future': True,
                'option': None,
                'createStopMarketOrder': True,
            },
            'options': {
                'fetchMarkets': {
                    'types': ['linear'],
                },
                'defaultSubType': 'linear',
                'leverageBrackets': None,
                'marginTypes': {},
                'marginModes': {},
                'fetchBalance': {
                    'useV2': True,
                },
            },
            'urls': {
                'api': {
                    'fapiPublic': 'https://fapi.asterdex.com/fapi/v1',
                    'fapiPublicV2': 'https://fapi.asterdex.com/fapi/v2',
                    'fapiPublicV3': 'https://fapi.asterdex.com/fapi/v3',
                    'fapiPrivate': 'https://fapi.asterdex.com/fapi/v1',
                    'fapiPrivateV2': 'https://fapi.asterdex.com/fapi/v2',
                    'fapiPrivateV3': 'https://fapi.asterdex.com/fapi/v3',
                },
                'www': 'https://asterdex.com',
                'doc': [
                    'https://docs.asterdex.com/product/aster-pro/api/api-documentation',
                    'https://github.com/asterdex/api-docs/blob/master/README.md',
                ],
            },
            # Extend/override only a few codes explicitly mentioned in Aster docs
            'exceptions': {
                'exact': {
                    '-4164': InvalidOrder,  # MIN_NOTIONAL
                    '-4135': InvalidOrder,  # INVALID_ACTIVATION_PRICE
                    '-4138': InvalidOrder,  # REDUCE_ONLY_MUST_BE_TRUE with closePosition
                    '-4139': InvalidOrder,  # ORDER_TYPE_CANNOT_BE_MKT (unable to cancel)
                    '-4141': BadRequest,    # SYMBOL_ALREADY_CLOSED
                },
            },
        })


